services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: false       # Allows optimizing the container by removing unused services; this also means
    # fetching services directly from the container via $container->get() won't work.
    # The best practice is to be explicit about your dependencies anyway.

    bind:
      $googleApiKey: '%google_maps.api_key%'
      $clients: !tagged_iterator google.client
      $parsers: !tagged_iterator google.parser

  Puwnz\GoogleMapsBundle\:
    resource: '../../'

  Puwnz\GoogleMapsLib\:
    resource: '%kernel.project_dir%/vendor/puwnz/google-maps-lib/src/'

  _instanceof:
    Puwnz\GoogleMapsLib\Common\Client\ClientInterface:
      tags: [ 'google.client' ]

    Puwnz\GoogleMapsLib\Common\Parser\ParserInterface:
      tags: [ 'google.parser' ]
